session.menuFile:	~/.fluxbox/menu
session.keyFile: ~/.fluxbox/keys
session.styleFile: /usr/share/fluxbox/styles/ ubuntu-light
session.configVersion:	13
session.screen0.toolbar.widthPercent: 0
session.screen0.strftimeFormat: %d %b, %a %02k:%M:%S
session.screen0.toolbar.tools:  prevworkspace, workspacename, nextworkspace, clock, prevwindow, nextwindow, iconbar
session.screen0.toolbar.autoHide: false
session.screen0.toolbar.visible: false